### ISSUE TITLE
Wrong cookbook link

### ISSUE THREAD

**Issue by flashultra** [feathersui/feathersui-website#28]
When I am on https://feathersui.com/learn/haxe-openfl/tool-tips/ page ,  clicking on the COOKBOOK link ( under the Last updated on 3/10/2022) lead to empty page

I think the file "website/sidebars.json" should be corrected . 
The line "haxe-openfl/cookbook/index" shold be "haxe-openfl/cookbook"

**Comment by joshtynjala** [comment]
It appears to be a bug in Docusaurus, the static site generator I use. Unfortunately, it won't let me switch to `"haxe-openfl-cookbook"`. When I do that, the link doesn't appear in the sidebar. I guess it'll just need to remain broken for now.
